name: Sync Wiki
on:
  push:
    branches: [ main ]

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure Git credentials
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Clone Wiki Repo
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.wiki.git wiki-repo
          cp -r wiki/* wiki-repo/
          cd wiki-repo
          git add .
          git commit -m "Update wiki from /wiki folder" || echo "No changes to commit"
          git push
